name: Run tasks on project
on:
  push:
    branches:
      - main # run the action on your projects default branch

jobs:
  tasks:
    name: Run tasks on project
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        # SENTRY_URL: https://sentry.io/
      with:
        environment: production
